name: 'Comment actions'

on: issue_comment

permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write

jobs:
  check_commands:
    runs-on: ubuntu-latest
    steps:
      - uses: ForgeForce/ForgeCommands@v1_new
        with:
          gh_app_key: ${{ secrets.GH_APP_KEY }}
          gh_app_name: ${{ secrets.GH_APP_NAME }}
          config_directory: ForgeForce/ActionsStore:configs@main
